version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trackmysub
      POSTGRES_USER: trackmysub
      POSTGRES_PASSWORD: trackmysub
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
